/**
 * ============================================================================
 * Timing Parser Module for NNTrainer Visualizer
 * ============================================================================
 * FILE: timingParser.js
 * 
 * This module parses model_timing.txt (generated by C++ backend)
 * and converts it into a format suitable for the webview visualizer.
 * 
 * ============================================================================
 */

const fs = require('fs');
const path = require('path');

/**
 * @class TimingParser
 * @description Parses NNTrainer timing data from model_timing.txt
 */
class TimingParser {
  constructor() {
    this.timing_data = new Map();
  }

  /**
   * @brief Parse timing data from text file
   * @param {string} filepath - Path to model_timing.txt
   * @returns {Promise<Object>} Parsed timing data structured for visualizer
   * 
   * @example
   * const parser = new TimingParser();
   * const timingData = await parser.parseTimingFile('./model_timing.txt');
   * // Returns:
   * // {
   * //   layers: [
   * //     {
   * //       name: 'input',
   * //       type: 'Input',
   * //       total_ms: 0.002,
   * //       forward_ms: 0.002,
   * //       backward_ms: 0,
   * //       weight_update_ms: 0
   * //     },
   * //     ...
   * //   ],
   * //   summary: {
   * //     total_time_ms: 12.537,
   * //     num_layers: 6,
   * //     slowest_layer: 'conv2d_1',
   * //     slowest_time_ms: 5.430
   * //   }
   * // }
   */
  async parseTimingFile(filepath) {
    return new Promise((resolve, reject) => {
      if (!fs.existsSync(filepath)) {
        reject(new Error(`Timing file not found: ${filepath}`));
        return;
      }

      fs.readFile(filepath, 'utf8', (err, data) => {
        if (err) {
          reject(err);
          return;
        }

        try {
          const result = this._parseContent(data);
          resolve(result);
        } catch (parseErr) {
          reject(parseErr);
        }
      });
    });
  }

  /**
   * @brief Synchronous version of parseTimingFile
   * @param {string} filepath - Path to model_timing.txt
   * @returns {Object} Parsed timing data
   */
  parseTimingFileSync(filepath) {
    if (!fs.existsSync(filepath)) {
      throw new Error(`Timing file not found: ${filepath}`);
    }

    const data = fs.readFileSync(filepath, 'utf8');
    return this._parseContent(data);
  }

  /**
   * @private
   * @brief Internal parsing logic - handles both newline-based and pipe-separated formats
   * @param {string} content - Raw file content
   * @returns {Object} Structured timing data
   */
  _parseContent(content) {
    const lines = content.split('\n').filter(line => line.trim().length > 0);
    const layers = [];
    let total_time_ms = 0;
    let slowest_layer = '';
    let slowest_time_ms = 0;

    for (const line of lines) {
      // Skip comment lines
      if (line.startsWith('#')) continue;

      // Parse line based on separator (space or |)
      const layer = this._parseLine(line);
      if (layer) {
        layers.push(layer);
        total_time_ms += layer.total_ms;

        // Track slowest layer
        if (layer.total_ms > slowest_time_ms) {
          slowest_time_ms = layer.total_ms;
          slowest_layer = layer.name;
        }
      }
    }

    return {
      layers: layers,
      summary: {
        total_time_ms: parseFloat(total_time_ms.toFixed(6)),
        num_layers: layers.length,
        slowest_layer: slowest_layer,
        slowest_time_ms: parseFloat(slowest_time_ms.toFixed(6))
      }
    };
  }

  /**
   * @private
   * @brief Parse a single line from timing data
   * @param {string} line - Line to parse
   * @returns {Object|null} Layer timing object or null if invalid
   * 
   * Supports two formats:
   * 1. Space-separated: "input Input 0.002 0.002 0 0"
   * 2. Pipe-separated with functions: "conv2d_1 Conv2D 5.430 | forward 2.1ms backward 3.33ms"
   */
  _parseLine(line) {
    const trimmed = line.trim();

    // Check if line contains pipe separator (function-level breakdown)
    if (trimmed.includes('|')) {
      return this._parseLinePipeFormat(trimmed);
    } else {
      return this._parseLineSpaceFormat(trimmed);
    }
  }

  /**
   * @private
   * @brief Parse space-separated format
   * @param {string} line - "input Input 0.002 0.002 0 0"
   * @returns {Object|null}
   */
  _parseLineSpaceFormat(line) {
    const parts = line.split(/\s+/).filter(p => p.length > 0);

    // Expected format: name type total_time forward_time backward_time weight_update_time
    if (parts.length < 5) {
      return null;
    }

    const [name, type, total, forward, backward, update = '0'] = parts;

    return {
      name: name,
      type: type,
      total_ms: parseFloat(total),
      forward_ms: parseFloat(forward),
      backward_ms: parseFloat(backward),
      weight_update_ms: parseFloat(update),
      functions: null // No function breakdown in this format
    };
  }

  /**
   * @private
   * @brief Parse pipe-separated format with function breakdown
   * @param {string} line - "conv2d_1 Conv2D 5.430 | forward 2.1ms backward 3.33ms weight_update 0.002ms"
   * @returns {Object|null}
   */
  _parseLinePipeFormat(line) {
    const [header, functions] = line.split('|').map(s => s.trim());
    const parts = header.split(/\s+/).filter(p => p.length > 0);

    if (parts.length < 3) {
      return null;
    }

    const [name, type, total] = parts;
    const funcs = this._parseFunctions(functions);

    return {
      name: name,
      type: type,
      total_ms: parseFloat(total),
      forward_ms: funcs.forward || 0,
      backward_ms: funcs.backward || 0,
      weight_update_ms: funcs.weight_update || 0,
      functions: funcs
    };
  }

  /**
   * @private
   * @brief Parse function-level timing breakdown
   * @param {string} funcStr - "forward 2.1ms backward 3.33ms weight_update 0.002ms"
   * @returns {Object} Functions with their timings
   */
  _parseFunctions(funcStr) {
    const functions = {
      forward: 0,
      backward: 0,
      weight_update: 0
    };

    if (!funcStr) return functions;

    // Match patterns like: forward 2.1ms, backward 3.33ms, weight_update 0.002ms
    const forward_match = funcStr.match(/forward\s+([\d.]+)\s*m?s?/i);
    const backward_match = funcStr.match(/backward\s+([\d.]+)\s*m?s?/i);
    const update_match = funcStr.match(/weight_update\s+([\d.]+)\s*m?s?/i);

    if (forward_match) functions.forward = parseFloat(forward_match[1]);
    if (backward_match) functions.backward = parseFloat(backward_match[1]);
    if (update_match) functions.weight_update = parseFloat(update_match[1]);

    return functions;
  }

  /**
   * @brief Get timing data as a summary table for logging
   * @param {Object} timingData - Output from parseTimingFile
   * @returns {string} Formatted table
   */
  getFormattedTable(timingData) {
    let output = '\n╔════════════════════════════════════════════════════════════╗\n';
    output += '║         NNTrainer Layer Execution Timing Report             ║\n';
    output += '╠════════════════════════════════════════════════════════════╣\n';

    for (const layer of timingData.layers) {
      const name = layer.name.padEnd(20);
      const type = layer.type.padEnd(12);
      const total = layer.total_ms.toFixed(4).padStart(10);
      output += `║ ${name} ${type} ${total} ms ║\n`;
    }

    output += '╠════════════════════════════════════════════════════════════╣\n';
    const summary = timingData.summary;
    output += `║ Total Execution Time:              ${summary.total_time_ms.toFixed(4)} ms ║\n`;
    output += `║ Total Layers:                      ${summary.num_layers}                     ║\n`;
    output += `║ Bottleneck Layer:                  ${summary.slowest_layer.padEnd(20)} ║\n`;
    output += `║ Slowest Time:                      ${summary.slowest_time_ms.toFixed(4)} ms ║\n`;
    output += '╚════════════════════════════════════════════════════════════╝\n';

    return output;
  }
}

// ============================================================================
// INTEGRATION: Add to extension.js
// ============================================================================
// At the top of extension.js:
// const TimingParser = require('./timingParser');

// In your command handler (e.g., visualizeModel command):
// async function visualizeModel(uri) {
//   const workspaceFolder = vscode.workspace.getWorkspaceFolder(uri);
//   const iniPath = uri.fsPath;
//   const folder = path.dirname(iniPath);
//
//   // Parse .ini and .bin (existing code)
//   const config = iniParser.parseINIFile(iniPath);
//   const binPath = path.join(folder, path.basename(iniPath, '.ini') + '.bin');
//
//   let weights = null;
//   if (fs.existsSync(binPath)) {
//     weights = binParser.parseBinaryFile(binPath, config.layers);
//   }
//
//   // NEW: Parse timing data if available
//   let timingData = null;
//   const timingPath = path.join(folder, 'model_timing.txt');
//   if (fs.existsSync(timingPath)) {
//     try {
//       const parser = new TimingParser();
//       timingData = parser.parseTimingFileSync(timingPath);
//       console.log(parser.getFormattedTable(timingData));
//     } catch (err) {
//       console.error('Failed to parse timing data:', err);
//     }
//   }
//
//   // Send to webview
//   panel.webview.postMessage({
//     command: 'displayModel',
//     config: config,
//     weights: weights,
//     timing: timingData  // NEW
//   });
// }

module.exports = TimingParser;
